version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  cassandra:
    image: "cassandra:3.11.4"
    ports:
      - "9042:9042"
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 50
    expose:
      - "9042"
  web:
    depends_on:
      - cassandra
    restart: always
    build: ./src
    working_dir: /src
    volumes:
      - ./src:/src
    command: mvn clean install spring-boot:run
    expose:
      - "8080"

